### ISSUE TITLE
Splunk search error

### ISSUE THREAD

**Issue by Fazx** [back2root/log4shell-rex#2]
Splunk throws an error when using the rex: Regex: unmatched closing parenthesis.
![image](https://user-images.githubusercontent.com/30384789/146120858-84825c0b-8479-47db-b19d-0e69df9c1b81.png)

and I'm wondering what is "%{" for because the attack payloads don't contain this string.
thanks.

**Comment by back2root** [comment]
We do need aditional escaping in SPL.
"%{" was a typo of "${". Better don't filter at all, otherwise you'll miss things, the RegEx would catch. (encoding)
