### ISSUE TITLE
Splunk Regex doesn't seem to work as pasted

### ISSUE THREAD

**Issue by PortWhisperer** [back2root/log4shell-rex#6]
The splunk regex isn't returning results. In testing it returned no results, missing even unobfuscated versions of the payload. Are the authors of the regex able to confirm?

**Comment by back2root** [comment]
Hi @PortWhisperer,

Oh, I see, we do need an additional test case.

![20-12-2021_232722](https://user-images.githubusercontent.com/9200239/146841836-08e75c8c-5401-492d-9521-ecea24e07331.jpeg)

But I think there is an issue if the attack pattern is not right at the beginning of the line.

Thank you for noticing that!
Will fix that in a moment.
